### ISSUE TITLE
vae/gan using selfies

### ISSUE THREAD

**Issue by jessielyons** [aspuru-guzik-group/selfies#101]
Hello, sincere apologies for bothering you. Can your team recommend/share a code example on how to use data based on SELFIES representation as input and do a denovo structure generation (vae/gan etc.) via optimization of property such as knockdown efficiency as an example?

Appreciate any guidance. I am looking for an example code from you using selfies only. I have also computed some structural properties using smiles input. I am familiarizing myself with your random smiles structure generator and stoned publications but not clear on how to do denovo generation via optimization of biological property. 

Thanks a lot, JL

**Comment by MarioKrenn6240** [comment]
Hi! There is one [VAE ](https://github.com/aspuru-guzik-group/selfies/tree/master/examples/vae_example) example at our github, otherwise try to use [STONED-SELFIES](https://github.com/aspuru-guzik-group/stoned-selfies) or [JANUS](https://twitter.com/akshat_ai/status/1522271170824835073?s=20).

I hope that helps,
Mario

**Comment by jessielyons** [comment]
Thanks so much Mario, really appreciate your message. You and your
colleagues are doing amazing science, fascinated by all the work. Still at
the learning stage for all this.
