### ISSUE TITLE
Selfies for most common substructure search

### ISSUE THREAD

**Issue by peiyaoli** [aspuru-guzik-group/selfies#105]
Hi, I am wondering if SELFIES could be used for most common substructure search?

Many thanks~

**Comment by MarioKrenn6240** [comment]
Hi @peiyaoli, thanks for your interest. SELFIES uses a representation where locally you cannot understand the substructure in every case. That's because of the overloading of symbols [(see the code paper, specifically Table 3)](https://pubs.rsc.org/en/content/articlelanding/2023/DD/D3DD00044C) which is necessary for introducing 100% robustness. Therefore, for substructure search, SELFIES are not ideal - but its easy to translate between SMILES and SELFIES (sf.decoder and sf.encoder), thus you can take advantage of the best from both worlds.
