### ISSUE TITLE
arxiv paper related questions

### ISSUE THREAD

**Issue by hkmztrk** [aspuru-guzik-group/selfies#2]
1- In Table 3, what are the letters for each representation, especially for SELFIES? Is SELFIES alphabet is the one described in Table 2? If so, is there way to generate these letters from the current SELFIES output?

2- In Table 3, QM9 dataset has 14 characters for the SELFIES alphabet, organic semiconductor dataset has 22 characters. Do these rules change from dataset to dataset? In our case, will these rules (number of characters) change if we use a database  for instance from Pubchem?

3 - We are having difficulties interpreting the Section 4.1 and Table 4. What do non-terminal symbols and the full alphabet correspond to?

The arxiv paper mentions the possibility of a workshop, and we would actually be interested in a short webinar as well.

**Comment by MarioKrenn6240** [comment]
Hello and thanks for your interest and your feedback! Let me answer your questions point by point:

**ad1)** Alphabet stands for the number of symbols (rule vectors) in the alphabet. For example, for QM9, SELFIES requires 14 rule vectors to represent all molecules. You can see in the grammar shown in Table2, that it involves exactly 14 columns (here denoted as A-N). Those are the 14 alphabet entries.  The largest molecule in QM9 translated to SELFIES has 21 symbols (all of those 21 symbols represent one of the 14 rule vectors in the alphabet).

The same is true for organic semiconductors. Those molecules involve more elements than QM9 molecules (for example, sulfur, chlorine, bromine), and therefore the alphabet is larger.

The alphabet you want to use depends on your dataset (or your preferences what your would like to use in your generator). If you use a dataset of molecules, which you have in the SMILES representation, then you could use the encoder from the package to produce SELFIES from each molecule, and afterwards could the unique elements (the version on github has a more human-readable output than the alphabet shown in the paper. in particular, all symbols of SELFIES are written in squared-brackets, for instance [C] for carbon.).

**ad2)** Part of your question is described above, but let me add some more details: If you use a small database, for instance molecules without sulfur (such as QM9), you dont need to use sulfur as part of your alphabet. If you use large database, the alphabet increases, but all symbols still have the same meaning in all databases. For example, [C] will always stand for carbon (or a number, if derived as non-terminal N), independent of the size of your alphabet.

**ad3)** The phrases come from formal grammars. A non-terminal symbol can be replaced, terminal symbols cannot be replaced. In Table 2, non-terminal symbols are **X_i** and **N**. If the string still contains these elements, the derivation will continue. If it doesnt contain any of those non-terminal symbols, the derivation of the string (molecule, or branch from molecule) is finished.
Now if you look at Table 2, there are several rule-vectors (A,B,...,N) which do not contain any non-terminal symbol (such as B, which corresponds to Fluorine. The reason is, that Fluorine can only form one bond, thus a further derivation of a string with Fluorine will lead to a semantical invalid molecule. The only exception here is if Fluorine is the first element. The initial state of the derivation if **X_0**, and you see in the column for X_0, rule-vector B has "F **X1**").
So one critizism could have been that SELFIES just uses more terminal symbols, and produces smaller molecules and is therefore more robust. That is why we performed a test which excludes all rule-vectors which do not include non-terminals (we removed A,B,C and D). The result shows that the valid molecules are of course much larger, and the validity is still significantly larger than for other representations.

Thank you for your interest in the workshop and/or webinar. We havent decided on the format. We will certainly post it here - furthermore if you give me your mail adresse, i will add you to our hopefully-soon-existing mailing list about this topic.

Please let me know about further questions. Thanks for the feedback, we'll use it to improve the paper and potentially add some more functionalities to the code.

best regards,
Mario
