### ISSUE TITLE
Encoder differences

### ISSUE THREAD

**Issue by jannisborn** [aspuru-guzik-group/selfies#26]
It seems there were some major updates in the release of package version 1.X.
I used to use `v0.2.4`, now I tried to switch to `1.0.1`. All unit tests are failing and from the [release message](https://github.com/aspuru-guzik-group/selfies/releases/tag/v1.0.1) it seems there were only minor changes.

E.g. with the old version

```py
>>>encoder('c1cnoc1')
'[c][c][n][o][c][Ring1][Ring2]'
```

The new version instead
```py
>>>encoder('c1cnoc1')
'[C][C][=N][O][C][Expl=Ring1][Branch1_1]'
```

Is this expected and considered a minor change? I mean mostly to go from `Ring2` token to `Branch1_1`. I have several similar cases (can report them if needed).
Can you maybe comment on whether you prefer users to use `1.0.1` instead of `v0.2.4`. Are there red flag errors in the old version? If I update now, I would need to repeat a chunk of work and retrain some generative models (e.g. since the vocabulary seems different). Also, is this version considered stable for the moment? If you plan to update the package again in a few weeks, I would probably wait before bumping up my dependency.

Thanks for the good work :)

**Comment by MarioKrenn6240** [comment]
Hi Jannis! The main difference concerning your example is that now SELFIES strings can work in a semantically correct way with aromatic rings. That is done by dearomatizing the SMILES and encoding the dearomatized version. That's the reason why your result now contains only non-aromatic symbols (in v1.0.0), while in v0.2.4 it contains aromatic symbols.

This would have the following effects: you have a dataset with molecules, including aromatic symbols. You create the alphabet from those molecules and use it in generative tasks. Before, aromatic symbols in generative tasks were not necessarily semantically correct. Now they are not used anymore (because we dearomatize all, and write bonds explicitly); so the generated molecules from the generative model will contain only valid molecules.

Version 0.2.4 works stable and can be used without a problem (we used it without issues), if you do not use aromatic symbols in the alphabet for generating new molecules. Apart from that, we extended scope (which seems to be not important for your applications), fixed a few minor bugs (for which workarounds can be applied) and the code is much faster.

In general, from what I understood, you can continue with 0.2.4 if you don't want to translate/retrain. If you want more specific infos, please provide more details.

Finally, yes, v1.0.1 is stable (passed all of our tests) and we don't plan to change anything except minor adaptions or bug fixes, which will be backwards compatible (i.e. what you do with v1.0.1, you can reuse with 1.0.x).

I hope that helps,
Mario

**Comment by MarioKrenn6240** [comment]
And now i just saw: the changes you refere to are from v1.0.0 to v1.0.1. Please see [changes from v0.2.4 to v1.0.0](https://github.com/aspuru-guzik-group/selfies/blob/master/CHANGELOG.md).

**Comment by jannisborn** [comment]
Perfect! Many thanks @MarioKrenn6240 for the prompt reply, that helped a lot. Thanks also for the pointer to the changelog, I had missed that one. I used 0.2.4 for generative tasks and the model worked fine in generating aromatic bonds.
I'm closing this issue now.
