### ISSUE TITLE
Wildcard Error message of encoder (and decoder)

### ISSUE THREAD

**Issue by DocMinus** [aspuru-guzik-group/selfies#41]
The try block in the encoder seems to check for wildcard in the molecule, and it works, except it doesn't print out the appropriate error message regarding the wildcard. 

I.e.
`smiles = "C[C@H](O)[C@@(*)C1=CC=CC=C1"`
encoder returns as a result (correctly) None. 
(side note: I personally would have used a regex matcher (`if re.match('[*]?', smiles): ....`) instead, but '*' statement seems to work!?)
Anyway, no message is printed out pointing to this issue. I am no good with try/except so I can't say what's going here, other than it doesn't seem to work as implied? 

Also, wouldn't it be better instead to check for the wildcard in the `smiles.split` loop? And while you are doing this, you could also check for R groups, thus eliminating e.g. the currently other open issue (where one can suspect you won't get a reply back....).

And finally, you return "None" as a result in the case of error. 
If you then submit None to the decoder, Python throws errors. It remains silent though if you submit a nonsense string (or simply an empty one, or a None (as string)), no error message as the code would imply. I get e.g. this:

```
  File "test.py", line 11, in <module>
    decoded_smiles = sf.decoder(None)  # SELFIES --> SMILES
  File "/home/alex/dev/selfies/selfies-master/selfies/decoder.py", line 35, in decoder
    for s in selfies.split("."):
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by MarioKrenn6240** [comment]
Thanks for this issue, we will loop into it, and fix the issue.

**Comment by MarioKrenn6240** [comment]
Dear DocMinus,

We have discussed the issue, and added a new section to the [main github file](https://github.com/aspuru-guzik-group/selfies#handling-invalid-inputs). You can use the `print_error=True` to write errors, and simply check for `None` to see whether errors occured. Those options/properties were "hidden" in the documentary before, your comment made it clear that this needs to be discussed in the main page. Thank you for that.

The problem with wildcards and other R-groups is the following: we translate aromatic strings to non-aromatic equivalences, where bond restrictions can be validated. This translation is undefined in principle when there are wildcards or R-groups.  Thus, we think we cant do 

If you have a specfic application where you want to use R or wildcards, please show it here, we can probably find a simple workaround. Also, because of your question i have tested a few possible workarounds, a simple one might work, and we might implement this in a future version.

Thanks,
Mario

**Comment by DocMinus** [comment]
Cheers.
No, I personally don't require R-groups or wildcards in this context, it was just something I stumbled upon when testing the selfies.
Regarding the print_error = True, thanks for the tip and the updated documentation.
From my perspective, we can close this issue.
