### ISSUE TITLE
Mistakes on encoder/decoder nitro group

### ISSUE THREAD

**Issue by gtteixeira** [aspuru-guzik-group/selfies#53]
Hello everyone

I was performing some tests and get mistakes from selfies to smiles with nitro groups, generating  N,N-Dihydroxyamine

 follow code

`import selfies as sf 
import rdkit 
from rdkit import Chem 
from IPython import display

def evalSmilesAndSelfies(input):
    strucFromSelfies = sf.decoder(sf.encoder(input))
    ms = [Chem.MolFromSmiles(smi) for smi in (input,strucFromSelfies)]
    fromSmiles  = 'fromSmiles:\n' + input
    fromSelfies  = 'fromDecodedSelfies:\n' + strucFromSelfies
    names = [fromSmiles, fromSelfies]
    img = Chem.Draw.MolsToGridImage(ms,molsPerRow=2,subImgSize=(300,300),legends=[name for name in names])
    return display.display(img), print(f'smiles: {input},selfies: {strucFromSelfies}, encoded: {sf.encoder(input)}')`

results

![image](https://user-images.githubusercontent.com/28991408/123551083-a1f80280-d746-11eb-8e3b-5ee15bfec26d.png)

![image](https://user-images.githubusercontent.com/28991408/123551097-b805c300-d746-11eb-9578-82604a9fb9c7.png)

when I use charged version the nitro group is ok

![image](https://user-images.githubusercontent.com/28991408/123551127-d966af00-d746-11eb-9bf3-2082c7cc8931.png)

It may caused by a mistake in decoder to smiles when dealing with 

-N(=O)=O

because de Selfies version before decoder  is apparently ok
[C][N][Branch1_2][C][=O][=O]

thanks

**Comment by MarioKrenn6240** [comment]
Dear gtteixeira,
Thank you for your issue.

The problem is actually a chemistry question, on whether you want to consider pure octet rules or allow hypervalences. A very related issue was raised some months ago, and we have made an additional options in SELFIES, please see [this explanation](https://github.com/aspuru-guzik-group/selfies/issues/44#issuecomment-805447452).

In your specific case:
`sf.decoder(sf.encoder('CN(=O)=O')) # leads to 'CN(O)O'
sf.decoder(sf.encoder('CN(=O)=O'),constraints='hypervalent') # leads to 'CN(=O)=O'
`

Let me know whether that helps.

best regards,
Mario
