### ISSUE TITLE
Questions for the grammar

### ISSUE THREAD

**Issue by hwidong-na** [aspuru-guzik-group/selfies#67]
Hi,

Thanks for your effort to keep updating SELFIES. I'm confused the grammar in the [recent release](https://github.com/aspuru-guzik-group/selfies/tree/v2.0.0), as the encoding result is different from [the original paper](https://iopscience.iop.org/article/10.1088/2632-2153/aba947) for the example molecule 3,4-Methylenedioxymethamphetamine (MDMA).

```
>>> import selfies as sf
>>> sf.encoder("CNC(C)CC1=CC=C2C(=C1)OCO2")                                                       
'[C][N][C][Branch1][C][C][C][C][=C][C][=C][C][=Branch1][Ring2][=C][Ring1][=Branch1][O][C][O][Ring1][=Branch1]'
```

I used RDKit version `2020.09.1`.

Thanks in advance.

**Comment by alstonlo** [comment]
Hi @hwidong-na, 

The SELFIES from the original paper corresponds to v0 of `selfies`. Since then, we have improved and generalized the framework in order to support a wider variety of molecules. To do so, some syntax and grammar changes were made. 

We are currently working on a technical code paper that will fully explain the updated library. In the meantime, the [documentation](https://selfiesv2.readthedocs.io/en/v1.0.4/tutorial.html) gives an informal explaination about the grammar in SELFIES v1.0.4. In v2, we did make some additional changes, and these are documented in the [CHANGELOG](https://github.com/aspuru-guzik-group/selfies/blob/master/CHANGELOG.md).

Thank you for the question! If you have any further questions about the syntax and grammar, please feel free to ask below!
