### ISSUE TITLE
Constants.py

### ISSUE THREAD

**Issue by Ramb0a** [aspuru-guzik-group/selfies#74]
Dumb question while working on rewriting selfies in C:

Is there a specific reason that ELEMENTS, ORGANIC_Subsets etc are dictionaries and not arrays(lists) in the [constants.py](https://github.com/aspuru-guzik-group/selfies/blob/master/selfies/constants.py) file? 

I assume the capitalization means they won't change but are they dictionaries because there is the expectation that they will grow via user customisation? Asking before I go down the wrong optimisation rabbit hole.

Will delete if too dumb a question.

**Comment by alstonlo** [comment]
Hi @Ramb0a, 

Sorry for the delay! To be precise, `ELEMENTS` and `ORGANIC_SUBSET` in the `constants.py` file are Python sets, and there is no expectation for them to grow via user customization. The reason they are sets (as opposed to Python lists) is because checking membership in a set is much more efficient!

**Comment by Ramb0a** [comment]
Ah ok - so these constants never get iterated upon - these are just going to be checked for contain. Will delete question.
