### ISSUE TITLE
Limitations of SELFIES to represent stereochemistry

### ISSUE THREAD

**Issue by sphuber** [aspuru-guzik-group/selfies#76]
I was wondering what types of stereochemistry can be represented by SELFIES. The answer to a similar but not identical question raised in #38 was responded to by referring to the CHANGELOG of `v1.0`. It seems that that version simply brought SELFIES up to parity with SMILES. The latter only supports tetrehedral centers and chirality along double bonds, however, other forms are not supported: square planar, octahedral, trigonal-bipyramidal. Although it seems the [OpenSMILES](http://opensmiles.org/opensmiles.pdf) specification does include these latter three cases. As far as I am aware, axial and planar chirality are not supported in either SMILES or OpenSMILES. What is the support of these cases in SELFIES?

**Comment by MarioKrenn6240** [comment]
Hi @sphuber, thanks for your question. SELFIES can handle all stereochemistry that SMILES can handle. That is, because we have a loss-less translator between SMILES and SELFIES. I agree, there are much more complex stereochemistry details which at the moment cannot be described with _and_ string-based representation (also not with adjacency-matrix based methods, sometimes called "graph methods"). We are discussing these issues right now in a paper that is the result of a recent workshop on SELFIES. Shall be out in the beginning of 2022.

best regards,
Mario

**Comment by sphuber** [comment]
Thanks for the info Mario. If possible, would be great to have a link to the publication in this thread once it is out for reference. Then this issue can probably be closed.

**Comment by hjuinj** [comment]
@sphuber  I believe this is the paper https://arxiv.org/abs/2204.00056
